import camelToSnake from '@lib/camelToSnake'

const listOfComponents = [
  'Avatar',
  'Button',
  'ButtonGroup',
  'Checkbox',
  'ContentTitle',
  'Chart',
  'ChartLineBlank',
  'CodeHighlight',
  'CodeHighlightContainer',
  'Divider',
  'Dropdown',
  'DropdownItem',
  'EmojiHeadline',
  'FormInputGroup',
  'Headline',
  'HeadlineDesc',
  'Input',
  'MapPinCircle',
  'NavLink',
  'NavBurger',
  'NavLinkDark',
  'NavLinkSecondary',
  'NavLinkTwo',
  'NavTitle',
  'NavSection',
  'NavSectionTitle',
  'OutsideClickHandler',
  'ProgressBar',
  'Select',
  'StarRating',
  'Toggle',
  'Radio',
  'Tabs',
  'Uikon',
  'Widget',
  'WidgetBottomCta',
  'WidgetContent',
  'WidgetDoc',
  'WidgetTable',
  'WidgetHeader',
  'TopBar',
  'TopBarSection',
  'TopBarTitle',
  'TopBarLink',
  'TopBarLinkContainer',
  'Tag',
  'TagContainer',
]

const generateLinks = () => listOfComponents.sort().map(item => ({
  text: item,
  to: `/${camelToSnake(item)}`,
  component: require(`./${item}`).default, // eslint-disable-line
}))

export default generateLinks()
